// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stock_Master.Data;

#nullable disable

namespace Stock_Master.Migrations
{
    [DbContext(typeof(DBContent))]
    [Migration("20260801205041_SwitchToWarehouseTheme")]
    partial class SwitchToWarehouseTheme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stock_Master.Models.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productId"));

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("productId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            productId = 1,
                            category = "Електроніка",
                            price = 25000m,
                            productName = "Ноутбук"
                        },
                        new
                        {
                            productId = 2,
                            category = "Електроніка",
                            price = 8000m,
                            productName = "Монітор"
                        },
                        new
                        {
                            productId = 3,
                            category = "Периферія",
                            price = 1200m,
                            productName = "Клавіатура"
                        });
                });

            modelBuilder.Entity("Stock_Master.Models.Stock", b =>
                {
                    b.Property<int>("stockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("stockId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("stockId");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            stockId = 1,
                            ProductId = 1,
                            WarehouseId = 1,
                            quantity = 15
                        },
                        new
                        {
                            stockId = 2,
                            ProductId = 2,
                            WarehouseId = 1,
                            quantity = 30
                        },
                        new
                        {
                            stockId = 3,
                            ProductId = 1,
                            WarehouseId = 2,
                            quantity = 5
                        },
                        new
                        {
                            stockId = 4,
                            ProductId = 3,
                            WarehouseId = 2,
                            quantity = 50
                        });
                });

            modelBuilder.Entity("Stock_Master.Models.Warehouse", b =>
                {
                    b.Property<int>("warehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("warehouseId"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("warehouseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("warehouseId");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            warehouseId = 1,
                            address = "Суми, вул. Промислова 1",
                            warehouseName = "Головний склад"
                        },
                        new
                        {
                            warehouseId = 2,
                            address = "Суми, вул. Індустріальна 5",
                            warehouseName = "Склад №2"
                        });
                });

            modelBuilder.Entity("Stock_Master.Models.Stock", b =>
                {
                    b.HasOne("Stock_Master.Models.Product", "Product")
                        .WithMany("Stocks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stock_Master.Models.Warehouse", "Warehouse")
                        .WithMany("Stocks")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Stock_Master.Models.Product", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("Stock_Master.Models.Warehouse", b =>
                {
                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
