// <auto-generated />
using First_web_project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace First_web_project.Migrations
{
    [DbContext(typeof(DBContent))]
    partial class DBContentModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("First_web_project.Models.Class", b =>
                {
                    b.Property<int>("jobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("jobId"));

                    b.Property<string>("jobDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jobName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("jobId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            jobId = 1,
                            jobDescription = "Web",
                            jobName = ".Net dev"
                        },
                        new
                        {
                            jobId = 2,
                            jobDescription = "full stack",
                            jobName = "React"
                        },
                        new
                        {
                            jobId = 3,
                            jobDescription = "back",
                            jobName = "C++"
                        },
                        new
                        {
                            jobId = 4,
                            jobDescription = "game dev",
                            jobName = "C++"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
